### ISSUE TITLE
Need more features

### ISSUE THREAD

**Issue by rea1shane** [catppuccin/obsidian#17]
I like this theme very much. It looks simple and elegant. But is it too simple? Features such as the status bar are not visible on this theme. The same goes for mouse tips. I think adding some of the necessary features will make the theme easier to use.

ex: [obsidian-git](https://github.com/denolehov/obsidian-git) plugin on catppuccin theme(left) and [Minimal](https://github.com/kepano/obsidian-minimal) theme(right)

![441665594384_ pic](https://user-images.githubusercontent.com/93363751/195405430-2d7ba098-d440-4b7e-81ac-9ee15b41df7b.jpg)

**Comment by justTOBBI** [comment]
Hey, when I first used this theme I too didn't like the UI, so I made a minimal theme catppuccin port. If the owner wants, I can make a PR and add the theme as well as install instructions. If you want the theme in the meantime, hit me up @Discord: justTOBBI#6895

**Comment by mbeckrich** [comment]
Hey Shane, thanks for your thoughts. Obsidian is currently undergoing a major revamp of the app's default theme (see: https://github.com/catppuccin/obsidian/issues/16), which means I have not had time to work on the pre-0.16 theme while I get things ready for the app's new default css. In the meantime, you can remove these lines under the Hider section from the Catppuccin.css file in your Obsidian theme folder to restore all the default UI elements (although I cannot promise they will be styled correctly): https://github.com/catppuccin/obsidian/blob/main/scss/vendors/_plugins.scss#L163. (The missing UI elements you refer to are hidden using css, ironically, from the author of the Minimal theme's plugin!)

In the upcoming version of Catppuccin for 0.16, all of the UI elements will be visible by default and the appearance will be less opinionated overall (closer to a recolor). This has been a learning experience for me; I made the theme originally based around how I used the app, but going forward the theme will be less opinionated so that the wide variety of Obsidian use cases are respected. :) 

@justTOBBI Sorry to hear you do not like the UI. Maybe next time. :p For organizational purposes, it might be best to talk to Kepano (author of Minimal) and see if he will accept a PR for your Catppuccin Minimal.

**Comment by rea1shane** [comment]
@justTOBBI Hey, thank you for your willingness to share your theme. I'd like to see how the next version of Catppuccin theme experience first. I will contact you if I still need it after using new version. In the meantime I think make a PR to add Catppuccin to Minimal is a nice idea ([obsidian-minimal-settings](https://github.com/kepano/obsidian-minimal-settings)).

@mbeckrich Thanks for your work and looking forward to the next version. The current version is not really friendly for new Obsidian user, when I use it I felt that a lot of information or features was missing, especially since I wasn't familiar with Obsidian. But it's good-looking and simple enough, and I think I'll like it even more once I'm familiar with Obsidian.

**Comment by mbeckrich** [comment]
Appreciate the kind words! I apologize for its lack of user friendliness. I mostly use the command palette in Obsidian and should have made other use cases a higher priority. :) Like I said, the 0.16 version will be much more straightforward. Would love to hear your feedback on it when it comes out!

**Comment by rea1shane** [comment]
@mbeckrich Hey, Obsidian new version is here. Remind me when you're done. Thank you for your hard work.

**Comment by mbeckrich** [comment]
Thanks for your patience! Anubis in the Discord and I are making good progress on the theme update. If you would like to experiment with it now, grab https://github.com/catppuccin/obsidian/blob/development/theme.css and https://github.com/catppuccin/obsidian/blob/development/manifest.json, then place them in a folder called "Catppuccin" inside your Obsidian themes folder, like so:

![image](https://user-images.githubusercontent.com/88514414/195965241-2af79298-c07a-4766-b1e0-550838177e58.png)

If you try it out, would love to hear any feedback you might have. I have a plan for it in my head, but any thoughts other users of it have would be awesome. We haven't touched things like typography yet, but colors are almost all in place. I would recommend getting the plugin Style Settings, if you don't have it already, and then you can use the accent colors Anubis set up in there.

**Comment by rea1shane** [comment]
Thanks to all developers! I have tried new version with Style Settings plugin. Everything seems working fine. As you said, this version just recolor.

Some thoughts:
1. **font**: Is updating fonts in your next plan? This version of the font looks no different from the default.
Also does the font used in the previous version works for other languages? I didn't see any changes in the Chinese font, and I'd like to know does Catppuccin organization has font for Chinese?
2. **notification**: The default notification is in the upper right corner of the window. There are too many infomations or buttons there. Can you change the location of the notification? Some editors put notifications in the bottom right corner, like VSCode or JetBrains' IDE. I think it's a good choice.
Another reason that makes the notification look less compelling to me is that it doesn't have much contrast. Whether to consider using the accent color as the background color of the notification？
3. **visibility**: Layout and visibility determine the experience, and low visibility makes some information difficult to find, so is it possible to control visibility? Control by a plugin is an option, like [obsidian-minimal-settings](https://github.com/kepano/obsidian-minimal-settings).
4. **layout**: Looking forward to new layout.

Overall everything is great, configurable feature is also a good direction, but it may tends to increase the cost of use and away from simplicity. Moderate configurability is still good and no need to give users too much choice.

I'm a new Obsidian user, and my work hasn't migrated to this yet, so I can only offer these thoughts for now, and will follow up with more thoughts by issues.

Hope future changes can continue elegant and simple. Looking forward to the next update ~

**Comment by mbeckrich** [comment]
Hey Shane, thanks for your thoughtful reply.

1) Yes, this is next in my plan. In the meantime, you can assign your own fonts in Obsidian by going to Settings -> Appearance and changing the font to one you prefer. I'm not sure regarding Chinese -- if you change the fonts in Obsidian's settings, does that solve your problem? If there is a specific font you need for me to include in the theme, let me know and I will put it in there.

2) Can you provide a screenshot example of the notifications you are referring to? Are they coming from a plugin? I can definitely make some changes here once we ship the initial 1.0 compatible theme. My goal is to have the Catppuccin theme out by Monday, so some things, like UI changes that require some experimentation to get to look nice, will take a backseat (but I will get them done ASAP!). 

3) Are you referring to contrast between font color and background? If so, I agree, and am planning to expose as many related settings as possible in the Style Settings plugin so that people who prefer more/less contrast will be able to tweak things to their liking. 

4) Yes, changes to the layout are on my roadmap. They will take a little longer to get to so that I can meet our release deadline, but I promise there will be some modifications coming! 

Thank you again. :)

**Comment by rea1shane** [comment]
Hey Marshall:
1. Yes, Obsidian setting is a solution to change font. Of course, theme with font will be more easy to use, glad to hear this is your next step.
Default Chinese font is already suitable. Chinese font don't need to be too personalized or it will be hard to read. If I find a more suitable than default Chinese font I will recommend it to you. It doesn't matter now, skip it first.
2. Yes, they are coming from [obsidian-git](https://github.com/denolehov/obsidian-git), like below:
    <img width="371" alt="image" src="https://user-images.githubusercontent.com/93363751/196017284-3d4f0a7b-9aa8-4943-932e-7d571e6bfccc.png">
As you see, there are too many elements around it and the contrast between notification background and window background is too low, these makes it look very unobtrusive and have unclear boundaries. I'd like this, more effective for notification:
    ![1](https://user-images.githubusercontent.com/93363751/196017852-825dcd3e-92c5-42bb-87e2-6deb1a7bbab1.png)
I don't know if there are other sources of notifications and if they can be setting in a same place.
3. I referred to contrast between notification background and window background, but what you said is also a point to consider. I prefer to editor have higher contrast and other areas have lower contrast. It will make the editor stand out more in the whole and can focus on writting rather than others, like this:
    ![2](https://user-images.githubusercontent.com/93363751/196018868-f002d184-618a-4d46-a336-87bfaad1d0be.png)
I think guiding focus through contrast, size, and weight is a necessary. Current version does this well.

In my mind, good preset is more satisfying than settable. Hope and believe this theme can make people feel satisfied even if they don't set anything.

I am not a designer and above thoughts are subjective and may contain some errors. Thank you for your listening. May your theme become more popular.

**Comment by mbeckrich** [comment]
Hey Shane, thanks for your ideas. I have a better sense of what you're looking for now. 

I will install the git plugin and take a swing at putting it in a better location. 

Totally have the same preference for having a solid pre-configured theme, rather than leaving users to start from scratch. FWIW, I am not a designer either (this is probably obvious). I was using Obsidian a lot early on in Catppuccin's development, noticed there had been an open issue for an Obsidian theme for a while and decided to give it a go. The social/organizational/UX side of this is all pretty new for me, so I am trying to be openminded and learn from people's feedback. :)

**Comment by mbeckrich** [comment]
Shane, the theme has been updated for compatibility with 1.0.0. Feel free to give it a try and let me know your thoughts (development will be ongoing).

**Comment by rea1shane** [comment]
> Feel free to give it a try and let me know your thoughts

No problem. Recently there are some other things so it may take a while.

And you can hit me up @discord: rea1shane#6075

**Comment by mbeckrich** [comment]
Sounds good. Closing since this is about the pre-1.0.0 theme, but feel free to jump in the Obsidian thread in the Catppuccin Discord any time.
