### ISSUE TITLE
[Bug] Search suggestion note is not readable for hovered items

### ISSUE THREAD

**Issue by onnyyonn** [catppuccin/obsidian#26]
The search suggestion title changes color for a hovered item, but the search suggestion notes don't, which may make theme unreadable. The following screenshots illustrate the issue:

**Current Behavior:**
![Screenshot_20221025_031739](https://user-images.githubusercontent.com/963267/197709032-652ef168-7e81-4bae-9a59-86865a51b8e6.png)

**Desired Behavior:**
![Screenshot_20221025_031820](https://user-images.githubusercontent.com/963267/197709274-aa63b41d-7462-4b43-a28e-70fb4da9c82c.png)

**Possible Fix:**
```
.suggestion-item.is-selected .suggestion-note{
  color: var(--text-on-accent);
}
```

**Comment by mbeckrich** [comment]
Thanks, will fix in the morning! On Oct 25, 2022, at 1:27 AM, Anamitra Saha ***@***.***> wrote:﻿
The search suggestion title changes color for a hovered item, but the search suggestion notes don't, which may make theme unreadable. The following screenshots illustrate the issue:
Current Behavior:

Desired Behavior:

Possible Fix:
.suggestion-item.is-selected .suggestion-note{
  color: var(--text-on-accent);
}

**Comment by mbeckrich** [comment]
Okay, should be fixed in https://github.com/catppuccin/obsidian/commit/2c3a0bf6eb5efcc701a7c929d214e61890a224d8. I think the issue was due to the Better Command Palette plugin styling -- I could not replicate the problem without installing and using the plugin. I have also gone ahead and adjusted some of the css the plugin uses so that it has similar margins/padding to the rest of the theme. If you want to make any changes yourself, use the `.better-command-palette` selector. Let me know if you run into further issues!
