### ISSUE TITLE
Vim Block Cursor Issues

### ISSUE THREAD

**Issue by Shylexx** [catppuccin/obsidian#29]
Hiyo,

I am having some issues with the block cursor with the vim bindings enabled, it appears almost invisible besides some slight flickering on the hovered character since the latest release, my older vaults using release 0.2.2 seem to be working fine but 0.2.8 appears to be having the issue.
Hopefully this is alright to leave here and not being repeated, couldn't see anything about it elsewhere so I thought i'd leave it here.

**Comment by mbeckrich** [comment]
Update: So, the "broken stuff" I thought I saw was that I couldn't style the css of the cursor and thought maybe I had a specificity issue. However, some googling makes it seem like the css in the app theme is outdated (or for older versions of the app): https://forum.obsidian.md/t/cursor-styling-since-0-14-15/38721 and that the only thing that can be styled now is caret-color.

Currently, for me, the block cursor flashes lavender over the text in the default palette and responds to changes in the `--ctp-accent:` variable. I've tried a couple of the Style Settings accents and everything seems to work about as expected there. The only thing I notice is that if I tab out, the block cursor becomes an empty red rectangle, but I assume that's supposed to happen? (Sorry, more of an emacs guy :p)

I'll look around a little more, but if you could get a gif/image of the issue, that would be awesome. Thanks!

**Comment by plimeor** [comment]
@mbeckrich I have the same problem. I found that `--ctp-accent` does not exists in my Obsidian. 

🧐 Where do these `--ctp-*` variables come from?

<img width="518" alt="CleanShot 2022-11-08 at 14 18 07@2x" src="https://user-images.githubusercontent.com/49034188/200489495-b25c1352-c87f-4cd7-90b5-b468323fe630.png">

**Comment by mbeckrich** [comment]
> @mbeckrich I have the same problem. I found that `--ctp-accent` does not exists in my Obsidian.
> 
> 🧐 Where do these `--ctp-*` variables come from?

They're created here: https://github.com/catppuccin/obsidian/blob/main/scss/base/_ctp-style-settings.scss#L808 and found in the theme.css file if you cmd/ctrl+f for `/* ------------------Selecting Accents------------------- */`.

I found the issue, though. The full palette became detached from the theme in 0.2.8 if a user does not have Style Settings installed (this is why I did not notice until just now when I checked on my Windows computer). Should be a quick fix.

**Comment by mbeckrich** [comment]
> @mbeckrich I have the same problem. I found that `--ctp-accent` does not exists in my Obsidian.
> 
> 🧐 Where do these `--ctp-*` variables come from?
> 
> <img alt="CleanShot 2022-11-08 at 14 18 07@2x" width="518" src="https://user-images.githubusercontent.com/49034188/200489495-b25c1352-c87f-4cd7-90b5-b468323fe630.png">

They're created here: https://github.com/catppuccin/obsidian/blob/main/scss/base/_ctp-style-settings.scss#L808 and found in the theme.css file if you cmd/ctrl+f for `/* ------------------Selecting Accents------------------- */`.

I found the issue -- the

**Comment by mbeckrich** [comment]
This should be fixed in https://github.com/catppuccin/obsidian/commit/6ee23d86ce5909cacc9ae8740e5afa6fa3d5b095 after updating your version of the theme. This is reverts yesterday's breaking change; I'm sick, so will do a real fix tomorrow.

**Comment by Shylexx** [comment]
I had a look myself and using Style Settings definitely seems to make it work, so I shouldnt have any issues anymore from that point of view, I've left a gif of the exact issue I was having without it, assuming that Style Settings isnt meant to be a hard dependency, although if it is then I can only apologise for reporting an issue of not using the plugin 
![catppuccinblock](https://user-images.githubusercontent.com/84759985/200535566-1826ec23-9040-4e6a-bb55-3bb4ef471641.gif)

**Comment by mbeckrich** [comment]
The plugin should not be a requirement to use the full palette theme — I just made a change and forgot to make sure everything still worked as it should without the plugin, so thank you for bringing it to my attention!On Nov 8, 2022, at 3:03 AM, Alex Dauncey ***@***.***> wrote:﻿
I had a look myself and using Style Settings definitely seems to make it work, so I shouldnt have any issues anymore from that point of view, I've left a gif of the exact issue I was having without it, assuming that Style Settings isnt meant to be a hard dependency, although if it is then I can only apologise for reporting an issue of not using the plugin

**Comment by mbeckrich** [comment]
This should all be corrected as of https://github.com/catppuccin/obsidian/commit/464885b49c76e805eb2ab9a2ec05f05556fa6534 and last night's hack-y temporary fix has been removed.

Style Settings should not be needed to get the default full palette theme, so you can uninstall it if it's not of use to you otherwise. Closing the topic for now, but let me know if either of you run into further issues. Sorry for the mess. :)
