### ISSUE TITLE
Tab headers colors issue with stacked tabs

### ISSUE THREAD

**Issue by kerbless** [catppuccin/obsidian#33]
The tab headers of unfocused tabs behave weirdly when in "stacked" mode. The video explains it all:

https://user-images.githubusercontent.com/32358946/202852646-390df0dc-010b-4fb5-9c44-7de2d586ff49.mp4

I don't have tame to submit a PR but it probably has something to do with the foreground color of the "workspace-tab-header-inner" css class.

P.s. absolutely love your theme!

**Comment by mbeckrich** [comment]
Thank you so much! I will fix it today. There are some selectors specific to the stacked tabs that I probably didn’t account for when making changes the other day. Appreciate the included video, too. 👍 On Nov 19, 2022, at 6:18 AM, kerbless ***@***.***> wrote:﻿
The tab headers of unfocused tabs behave weirdly when in "stacked" mode. The video explains it all:
https://user-images.githubusercontent.com/32358946/202852646-390df0dc-010b-4fb5-9c44-7de2d586ff49.mp4
I don't have tame to submit a PR but it probably has something to do with the foreground color of the "workspace-tab-header-inner" css class.
P.s. absolutely love your theme!

**Comment by mbeckrich** [comment]
This should be fixed in the most recent update (0.2.14). I will leave this issue open in case anyone else runs into trouble here, because I may have missed some things. In the case of stacked tabs, only the text should change color on highlight now (as the 'tab' is technically 100% of the height; I experimented with reducing the height but know some people use long file names). There is a huge mess of css I need to fix related to the tabs, but if anyone is tweaking things on their own, the key is the .workspace-tabs.mod-stacked selector when changing the stacked tabs.
