### ISSUE TITLE
Excalidraw support with paletton

### ISSUE THREAD

**Issue by quantumfate** [catppuccin/obsidian#50]
I setup my excalidraw in a way so that my drawing notes match my obsidian colors. It would be great if this plugin or catpuccin itself had a integration with excalidraw. Maybe that is an upstream related issue to support paletton.com

Excalidraw in obsidion allows you to import color palettes with paletton.

**Comment by mbeckrich** [comment]
Thanks for the suggestion. Excalidraw been on my todo list for ages and I just haven’t gotten to it yet. I’m going to add it as part of the rewrite, though. I’m not super familiar with it so it might take a bit more time, but I’ll get it in ASAP. 😊 My goal is to get the rewrite out within the next week or so, real life permitting. I will update you here when Excalidraw has been added.On Sep 10, 2023, at 1:39 PM, Leon Connor Holm ***@***.***> wrote:﻿
I setup my excalidraw in a way so that my drawing notes match my obsidian colors. It would be great if this plugin or catpuccin itself had a integration with excalidraw. Maybe that is an upstream related issue to support paletton.com
Excalidraw in obsidion allows you to import color palettes with paletton.

**Comment by quantumfate** [comment]
I will paste my Excalidraw template here as you might find it useful. Note that I'm intentionally using light mode setting even though I use obsidian in dark mode. I'm doing that because if I used dark mode, excalidraw would invert all colors into light mode - It's increadibly confusing I know.

```txt
---

excalidraw-plugin: parsed
tags: [excalidraw]
excalidraw-export-dark: false

---
==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠==


# Text Elements
%%
# Drawing
```json
{
	"type": "excalidraw",
	"version": 2,
	"source": "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.9.19",
	"elements": [],
	"appState": {
		"theme": "light",
		"viewBackgroundColor": "#1e1e2e",
		"currentItemStrokeColor": "#1e1e1e",
		"currentItemBackgroundColor": "transparent",
		"currentItemFillStyle": "hachure",
		"currentItemStrokeWidth": 1,
		"currentItemStrokeStyle": "solid",
		"currentItemRoughness": 1,
		"currentItemOpacity": 100,
		"currentItemFontFamily": 1,
		"currentItemFontSize": 20,
		"currentItemTextAlign": "left",
		"currentItemStartArrowhead": null,
		"currentItemEndArrowhead": "arrow",
		"scrollX": 847.5,
		"scrollY": 654.0625,
		"zoom": {
			"value": 1
		},
		"currentItemRoundness": "round",
		"gridSize": 20,
		"gridColor": {
			"Bold": "#48486FFF",
			"Regular": "#2C2C44FF"
		},
		"currentStrokeOptions": {
			"highlighter": false,
			"hasOutline": false,
			"outlineWidth": 0,
			"constantPressure": false,
			"options": {
				"smoothing": 0.5,
				"thinning": -1,
				"streamline": 0.5,
				"easing": "linear",
				"start": {
					"taper": 5,
					"cap": false,
					"easing": "linear"
				},
				"end": {
					"taper": 5,
					"cap": false,
					"easing": "linear"
				}
			}
		},
		"previousGridSize": 20,
		"frameRendering": {
			"enabled": true,
			"clip": true,
			"name": true,
			"outline": true
		}
	},
	"files": {}
}
```
%%
```

**Comment by mbeckrich** [comment]
Fantastic! Thanks so much. On Sep 11, 2023, at 4:54 AM, Leon Connor Holm ***@***.***> wrote:﻿
I will paste my Excalidraw template here as you might find it useful. Note that I'm intentionally using light mode setting even though I use obsidian in dark mode. I'm doing that because if I used dark mode, excalidraw would invert all colors into light mode - It's increadibly confusing I know.
---

excalidraw-plugin: parsed
tags: [excalidraw]
excalidraw-export-dark: false

---
==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠==


# Text Elements
%%
# Drawing
```json
{
	"type": "excalidraw",
	"version": 2,
	"source": "https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.9.19",
	"elements": [],
	"appState": {
		"theme": "light",
		"viewBackgroundColor": "#1e1e2e",
		"currentItemStrokeColor": "#1e1e1e",
		"currentItemBackgroundColor": "transparent",
		"currentItemFillStyle": "hachure",
		"currentItemStrokeWidth": 1,
		"currentItemStrokeStyle": "solid",
		"currentItemRoughness": 1,
		"currentItemOpacity": 100,
		"currentItemFontFamily": 1,
		"currentItemFontSize": 20,
		"currentItemTextAlign": "left",
		"currentItemStartArrowhead": null,
		"currentItemEndArrowhead": "arrow",
		"scrollX": 847.5,
		"scrollY": 654.0625,
		"zoom": {
			"value": 1
		},
		"currentItemRoundness": "round",
		"gridSize": 20,
		"gridColor": {
			"Bold": "#48486FFF",
			"Regular": "#2C2C44FF"
		},
		"currentStrokeOptions": {
			"highlighter": false,
			"hasOutline": false,
			"outlineWidth": 0,
			"constantPressure": false,
			"options": {
				"smoothing": 0.5,
				"thinning": -1,
				"streamline": 0.5,
				"easing": "linear",
				"start": {
					"taper": 5,
					"cap": false,
					"easing": "linear"
				},
				"end": {
					"taper": 5,
					"cap": false,
					"easing": "linear"
				}
			}
		},
		"previousGridSize": 20,
		"frameRendering": {
			"enabled": true,
			"clip": true,
			"name": true,
			"outline": true
		}
	},
	"files": {}
}
%%


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by mbeckrich** [comment]
Hey, sorry for the delay. I looked into this several months ago and found it might not be a great user experience if the theme is implemented in Obsidian itself vs. coming from the Excalidraw config you provided. I noticed at least one other theme author took Excalidraw config out of his css due to this and the difficulty of maintaining it. I think that leaves us with a couple options, if you are still interested:

1. You can see if there is a place for your config elsewhere in the Catppuccin org: https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md

2. We can try incorporating your config into this repo here. I would credit your account with the code in the commit as I have for past contributors and mention it in Style Settings and the readme. That said, I would also need to confirm with Obsidian that it is okay to include this file in the repo. As far as I know, there aren't any rules against it, but not sure off the top of my head.

I will close the issue for now, but please reopen if you want to pursue this further. Thanks!
