### ISSUE TITLE
Bug of todo list with deleted line

### ISSUE THREAD

**Issue by Les1ie** [catppuccin/obsidian#51]
code:
```
- [x] title
  balabala
```
it will be like this:
![image](https://github.com/catppuccin/obsidian/assets/28597662/3dff5c58-1a5d-4f83-8574-7f6a97a55e6c)

but i don't want the consequent paragraph has deleted line.

**Comment by mbeckrich** [comment]
Thanks, will take a look and fix soon!

**Comment by mbeckrich** [comment]
Can you give me a little more detail on this? I am trying to replicate it in Obsidian, but have not been able to. I definitely believe this could be an issue because of how lines of text work with the CSS in Obsidian. One thing you might try:

When the problem occurs, open the web inspector in Obsidian by pressing cmd+opt+i (or ctrl+shift+i on windows/linux). Press the dotted square with an arrow in the top left of your inspector area, which may be on the left side of the app for you, and hover your mouse over the problem area.

<img width="1272" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/1f78e918-cb47-409e-9283-8b206c4609ae">

Then, click on the problem area and send me a screencap of what shows up in the inspector's html area. It should look something like the below. This is what I see on my end, but, in your case, I suspect that 'balabala' is not being separated from `.cm-list-1` or something similar to that.

<img width="626" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/b1c4f18c-5ae8-4e53-a780-108a8512bc56">

**Comment by Les1ie** [comment]
I found that this issue only occurs in reading mode and is normal in editing mode.

Reading mode:
![image](https://github.com/catppuccin/obsidian/assets/28597662/61089419-e959-421c-b76d-d9a7776f39ba)

Editing mode:
![image](https://github.com/catppuccin/obsidian/assets/28597662/10f8d965-1df9-40d0-bf2b-403ec905cd3a)

**Comment by mbeckrich** [comment]
Hey, sorry, I missed the reply on this somehow. Thanks for that, though. I think this is due to how markdown formatting is rendered in general. This happens even in the default theme for me. If you are still running into this, likely what you will want to do is press enter twice after finishing your list, so that there is a gap between the final list item and your next line of text. See: https://about.gitlab.com/handbook/markdown-guide/#paragraphs-breaks-and-horizontal-lines 

This kind of friction occurs in a few Markdown editors, because we're seeing new lines in the editing mode, but when it gets processed according to the Markdown syntax rules, it looks different from the rendering we saw in the editor. As an example, here is IA Writer in editing mode and then reading mode:

<img width="558" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/0f24324c-6b61-4bc9-8cc8-1a08e811696a">

<img width="580" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/f9b68562-5d89-4f01-b4b0-255046aaf20e">

And in Obsidian's default theme, the same text:

<img width="400" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/4b3770f7-0e4d-43b4-aec6-77bdeeb5ce4d">

<img width="383" alt="image" src="https://github.com/catppuccin/obsidian/assets/88514414/cee49dd8-e6c1-45f8-959d-2219709d731e">

Obsidian is assuming that a single enter after a word means we want the next word to appear beneath it when rendered in reading mode, whereas IA Writer will wrap text until we hit enter twice. The hiccup then comes when Obsidian then follows Markdown rules with lists, because we're still expecting the assumption it made earlier. My memory of Markdown syntax is a little hazy, but this should be close. I will close this for now, but if you discover something else specific to the theme, let me know! Thanks, and sorry again!
