### ISSUE TITLE
Put all style settings into a single section

### ISSUE THREAD

**Issue by RyotaUshio** [catppuccin/obsidian#55]
Hi, thank you for this great theme. I love it.

I'd like to propose to put all style settings into a single or a few sections with "Catppuccin" in their names. Currently, the style settings pane looks like this:

<img width="655" alt="image" src="https://github.com/catppuccin/obsidian/assets/72342591/77bbb743-f57d-4b0f-a8fb-3b52d1b65b57">

It's hard to distinguish which section comes from this theme and which doesn't.

Ideally, it should be put in a single or a few sections, and these sections should have "Catppuccin" in their name. Otherwise, users will not be able to find out which section to open to tweak this theme.

You can refer to the Minimal theme. Every Minimal-related section is given a name with "Minimal" in it.

<img width="674" alt="image" src="https://github.com/catppuccin/obsidian/assets/72342591/6c77f237-f49e-4d3e-8fab-33ae2b94fdad">

Thank you!

**Comment by mbeckrich** [comment]
Thank you! This is really helpful feedback. I will add this into the theme rewrite. On Dec 19, 2023, at 10:39 AM, Ryota Ushio ***@***.***> wrote:﻿
Hi, thank you for this great theme. I love it.
I'd like to propose put all style settings into a single section. Currently, the style settings pane looks like this:
image.png (view on web)
It's hard to distinguish which section comes from this theme and which doesn't.
Ideally, it should be put in a single or a few sections, and these sections should have "Catppuccin" in their name. Otherwise, users will not be able to find out which section to open to tweak this theme.
You can refer to the Minimal theme. Every Minimal-related section is given a name with "Minimal" in it.
image.png (view on web)
Thank you!

**Comment by RyotaUshio** [comment]
Thank you!!

**Comment by mbeckrich** [comment]
This should be fixed in the latest update. Thanks for your patience!
