### ISSUE TITLE
codeblock width in editing mode not 100%

### ISSUE THREAD

**Issue by KulySocc** [catppuccin/obsidian#58]
Why is the width of the codeblock in editing mode not 100%? And is there an easy way to tweak it?

_editing_
![image](https://github.com/catppuccin/obsidian/assets/166226089/97504520-9e65-4a2d-a373-a30966c8ab01)

_reading_
![image](https://github.com/catppuccin/obsidian/assets/166226089/21830105-95a5-4006-938a-1556aa2a396e)

**Comment by mbeckrich** [comment]
It's particularly bad in your case because you have numbered lines off, but that's not intended. I have just pushed a fix for this in https://github.com/catppuccin/obsidian/commit/84c6d243e9be7bf4fcbb42933beaebb93bd3b213. Please reopen the issue if it is still broken for you after updating.

As to why, briefly, I used `ch` as the unit for `--file-line-width`. Changing it from 65ch back to 700px (the default) fixes this problem. It looks like relative-ish units are having `margin-right` added to code blocks, because the app's internal css is applying the variable to `.markdown-source-view.mod-cm6.is-readable-line-width .cm-content` and then again, inside of that, to `.markdown-source-view.mod-cm6.is-readable-line-width .cm-line`, which I did not catch when making the theme. So, I think relative units are getting applied to themselves.
