### ISSUE TITLE
Callout icons are not shifted vertically

### ISSUE THREAD

**Issue by imrehg** [catppuccin/obsidian#72]
Filling it as an issue, as I'm pretty sure it's unintentional. The icons preceding the callouts seem to be skewed (not placed in the centre, or at the right balanced place). This can be seen very well with the circlular icons already:

For example: 

```markdown
> [!info] Do we have a center?
```

will look like this in Catpuccin:

<img width="247" alt="Screenshot 2024-10-27 at 10 28 43" src="https://github.com/user-attachments/assets/6708d8d3-d0aa-45ba-b718-42c403bfdeff">

(the bottom of the circle is clearly lower than the baseline of the text), and like this in the Default theme:

<img width="252" alt="Screenshot 2024-10-27 at 10 28 55" src="https://github.com/user-attachments/assets/6ddd8eeb-b50c-4d66-a3dd-47298c1da19f">

where it seems to be in line with the text.

**Comment by mbeckrich** [comment]
Thank you for noticing this! Although I am not a typography expert, my suspicion is that this is due to the fonts in use. Obsidian uses a font called Lucide for its svg icons and one called Inter for its text. Catppuccin uses a font called [Vollkorn](http://vollkorn-typeface.com) for its editor text by default, but keeps Lucide at 18x18. Vollkorn ends up 'sitting' kind of high up (examples below), particularly when using the Info callout, with long descenders and probably a smaller height than Inter. For more info on part of what is going on here, you can check out: https://github.com/jantimon/text-box-trim-examples, https://blog.prototypr.io/to-choose-the-right-typeface-look-at-its-x-height-instead-d5ef0967d09c

Your second image looks like it is using Inter, which is the default font in Obsidian. For now, try changing `Settings -> Appearance -> Text font` to the font 'Inter' while using Catppuccin and see if you get something that looks a little more to your liking. If you are still seeing something off when using Inter, please reopen this issue and let me know, but, otherwise, this is a downside that could occur when using any font that isn't similar in design to Inter. I agree that there is a bit of an uncanny valley type of effect here, but I am not sure I currently have a quick solution that can take into account the many font families people can use.

All of this to say, I don't think this is a problem related to css per se (it exists using Vollkorn and the default theme, for example), but, rather, how different fonts interplay. (Which raises the question of whether Vollkorn is still the 'right' default for Catppuccin. Vollkorn was part of Catppuccin before Obsidian had callouts, so this was just not an issue at the time I picked it. I have mixed feelings on changing default fonts and, for now, it's easy enough for people to pick something they like better, if they so choose! Vollkorn isn't a system default, so I would need to think about how to swap it out but not 'take it away' from users who want to keep it. I do consider this lesson learned going forward. :))

Some examples, indicating what might be happening:

Inter:
<img width="613" alt="image" src="https://github.com/user-attachments/assets/7069953c-4785-460a-aa39-f91a94f8468f">

Vollkorn:
<img width="595" alt="image" src="https://github.com/user-attachments/assets/9299d453-26ac-45bb-b879-138eac02bca6">

SF Pro Rounded (a random comparison, but which also ended up not aligning perfectly):
<img width="603" alt="image" src="https://github.com/user-attachments/assets/b6f7e1af-bc01-42c6-8130-03ddf11029f6">

**Comment by imrehg** [comment]
Wow, such a detailed and informative feedback, thanks a lot! I'll keep an eye out, and indeed, there are alot of interplay between the different fonts and systems (I'm using Obsidian across Linux, MacOS, and Android, so can't _always_ tell what causing what issue, and even the trial-and-error can often lead to a wild goose chase).
Cheers!

**Comment by mbeckrich** [comment]
You’re very welcome!On Oct 27, 2024, at 8:26 AM, Gergely Imreh ***@***.***> wrote:﻿
Wow, such a detailed and informative feedback, thanks a lot! I'll keep an eye out, and indeed, there are alot of interplay between the different fonts and systems (I'm using Obsidian across Linux, MacOS, and Android, so can't always tell what causing what issue, and even the trial-and-error can often lead to a wild goose chase).
Cheers!
