### ISSUE TITLE
Contrast on Mermaid Diagrams is too low

### ISSUE THREAD

**Issue by thelooter** [catppuccin/obsidian#73]
Currently some Diagrams using Mermaid have very low contrast, making reading them near impossible. An example of this is the mindmap diagram.

![image](https://github.com/user-attachments/assets/a2d94d37-99c4-4b8c-95cc-854d1cc06a9b)

**Comment by mbeckrich** [comment]
Thanks, I've never used mindmaps in Obsidian, so was unaware of this. I think I have solved this problem in the latest update, but, in searching, I did come across a post from the Obsidian forums indicating this is something that affects the default theme as well: https://forum.obsidian.md/t/text-colors-for-mermaid-mindmap-graph-are-unreadable-in-dark-mode/68674

Because I am able to replicate this issue in the default theme (and Minimal), I am a little concerned there might be a "reason" it doesn't work as expected there, but, if so, I am sure someone will let me know at some point. :) 

I have made a few changes to how nodes are shown in the mindmap to standardize things a bit. Now it should use Catppuccin colors up to the eighth node in a mindmap (we could increase that number programmatically in sass if people regularly go beyond eight). I have changed the underline color to the node color for simplicity's sake, but if this creates an issue I am not aware of, or if something breaks with this update, please reopen and let me know!
