### ISSUE TITLE
Low Color Contrast for Links within Highlighting Markups

### ISSUE THREAD

**Issue by habaneraa** [catppuccin/obsidian#97]
Hello! I noticed that when links are included within highlighting markups (`==[title](link)==`), the background and foreground colors have low contrast, making them difficult to read.

For example, in the Catppuccin - Mocha theme, the issue looks like this:

![image](https://github.com/user-attachments/assets/58474016-ee49-4d9e-8815-153b2b60c2cd)

In comparison, the Obsidian default theme looks like:

![image](https://github.com/user-attachments/assets/cbf7d2c8-65ac-4034-90fd-eec66a0d474c)

It would be great if the contrast could be improved for better readability. Love this theme 😘

**Comment by mbeckrich** [comment]
Thanks! And good catch on this. I have experimented with a couple potential solutions, one where the highlight color as a whole changes and another where the highlighted link color changes. I don't love either, but obviously it can't stay how it is. On the whole, I think fewer people are impacted/surprised if I change the link color, especially because it does include the little icon indicating it's an external link. So, for now, highlighted links are now a dark color and given an underline, further indicating their link status (and to help clarify internal links in particular, which lack an icon). The fix should be applied in the recent update, but let me know if you run into further issues with this!
